version: '3'
services:  
  postgres:
    container_name: postgres-possessedprops
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432" 
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=possessedprops
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U possessedprops"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend-possessedprops
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=possessedprops
      - DB_USER=admin
      - DB_PASS=password
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db:
    driver: local
